stages:
  download_data:
    cmd: python src/download_data.py
    deps:
      - src/download_data.py
    outs:
      - data/AHH/AHH_stock_data.csv
      - data/APO/APO_stock_data.csv
  preprocess_data:
    cmd: python src/preprocess_data.py
    deps:
      - data/AHH/AHH_stock_data.csv
      - data/APO/APO_stock_data.csv
    outs:
      - data/AHH/processed/AHH_processed.csv
      - data/APO/processed/APO_processed.csv
  train_model:
    cmd: python src/train_model.py
    deps:
      - data/AHH/processed/AHH_processed.csv
      - data/APO/processed/APO_processed.csv
    outs:
      - models/AHH/AHH_model.pkl
      - models/APO/APO_model.pkl
